name: Release
on:
  release:
    types: [created]
  push:

jobs:
  clients:
    name: 'Generate GRPC clients'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.14.x'

      - uses: actions/cache@v1
        id: go-cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-${{ hashFiles('**/go.sum') }}

      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          protoc --version

      - name: Install dependencies
        run: make bootstrap

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - uses: actions/checkout@v2
        with:
          repository: markphelps/flipt-grpc-ruby
          path: ../flipt-grpc-ruby

      - uses: actions/checkout@v2
        with:
          repository: markphelps/flipt-grpc-go
          path: ../flipt-grpc-go

      - name: Generate clients
        run: |
          make clients
